<script setup lang="ts">
// Generated by 'vue-bevy'
import ui_demoReadme from '../../crates/ui_demo/readme.md'
import init  from 'virtual:vue-bevy/ui_demo.js'
import WebgpuNotes from '~/components/webgpu-notes.vue';
const gpu = (navigator as any).gpu;

tryOnMounted(async () => {
    if (gpu) {
        const wasm =  await init('virtual:vue-bevy/ui_demo.wasm');
        wasm.run();
    }
});

const router = useRouter()
const { t } = useI18n()
</script>

<template>
    <ui_demoReadme />
    <WebgpuNotes />
    <template v-if="gpu">
        Make sure canvas has focus <br />
        Hit F12 for editor<br />
        <canvas class="wasm" />
    </template>

    <button class="btn m-3 text-sm mt-6" @click="router.back()">
    {{ t("button.back") }}
    </button>

</template>

<style scoped>
.wasm {
    margin-left: auto;
    margin-right: auto;
}
</style>

<route lang="yaml">
meta:
    layout: wasm
</route>