// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MdiHandshakeOutline: typeof import('~icons/mdi/handshake-outline')['default']
    WasmCornellBox: typeof import('./components/WasmCornellBox.vue')['default']
    WasmDisco: typeof import('./components/WasmDisco.vue')['default']
  }
}

export { }
