[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.5.0", default-features = false, features = [
     "bevy_render2",
     "bevy_winit",
     "bevy_core_pipeline",
]}
bevy-inspector-egui = "0.6.1"
engine = { path = "../../engine" }
wasm-bindgen = "0.2.78"
rand = "0.8.4"

